### *Uso De Ferramentas De Aprendizado De Máquina Na Análise De Dados*
# <b>Caderno 01 - Uso do pacote **pandas** </b>
### Neste caderno iremos:
1. *Importar* o pacote pandas com o nome **pd**
2. *Criar* uma tabela de dados (**dataframe**) nova 3x3 com dados exemplo 
3. *Nomear* **colunas** e **linhas** de uma tabela de dados.
4. *Adicionar* ou *Remover* **colunas** ou **linhas** de uma tabela de dados
5. *Carregar* ou *Salvar* uma tabela de dados em formato ***csv***

In [1]:
# Importando o pacote pandas
import pandas as pd

In [2]:
# Criando uma tabela de dados 3x3 diretamente
tabela_1 = pd.DataFrame([['maça','amarelo',23],['goiaba','verde',11], ['banana', 'azul', 9]])

In [3]:
# Visualizamos a tabela criada. Observe a ausência de nomes nas linhas e colunas
tabela_1

        0        1   2
0    maça  amarelo  23
1  goiaba    verde  11
2  banana     azul   9

In [4]:
# Para melhorar nossa orientação, damos nomes às linhas e colunas
tabela_1.columns = ['Fruta', 'Cor', 'Dias']
tabela_1.index = ['P-01', 'P-02', 'P-03']

In [5]:
# Visualizamos novamente os dados...
tabela_1

       Fruta      Cor  Dias
P-01    maça  amarelo    23
P-02  goiaba    verde    11
P-03  banana     azul     9

In [6]:
# Adicionar nova coluna de dados
tabela_1['Valor'] = [22.50, 1.99, 2.99]

In [7]:
# Adicionar nova linha de dados
tabela_1.loc['P-04'] = ['laranja', 'violeta', '2', '7.31']

In [8]:
# Visualizamos novamente os dados...
tabela_1

        Fruta      Cor Dias Valor
P-01     maça  amarelo   23  22.5
P-02   goiaba    verde   11  1.99
P-03   banana     azul    9  2.99
P-04  laranja  violeta    2  7.31

In [9]:
# Remover uma coluna de dados
tabela_2 = tabela_1.drop('Cor', axis='columns')
tabela_2

        Fruta Dias Valor
P-01     maça   23  22.5
P-02   goiaba   11  1.99
P-03   banana    9  2.99
P-04  laranja    2  7.31

In [10]:
# Remover uma linha de dados
tabela_3 = tabela_1.drop('P-02', axis='index')
tabela_3

        Fruta      Cor Dias Valor
P-01     maça  amarelo   23  22.5
P-03   banana     azul    9  2.99
P-04  laranja  violeta    2  7.31

In [14]:
# Salvando uma tabela de dados em formato csv
tabela_1.to_csv('tabela_1.csv')

In [22]:
# Carregando uma tabela de dados em formato csv para uma tabela pandas
# Atenção para os caracteres separadores de colunas e decimal!!!
iris_data = pd.read_csv("iris_dataset.csv", sep=';', decimal=',', encoding='latin-1', index_col=0)
iris_data

FileNotFoundError: [Errno 2] No such file or directory: 'iris_dataset.csv'

### Dê uma olhada na ***cheat-sheet*** com estes e vários outros exemplos de funçoes do pacote pandas (arquivo *Pandas-Cheat-Sheet.pdf* disponível no drive do curso!)
### Agora teste seus conhecimentos manipulando a tabela com os dados do modelo Íris que você acabou de carregar! ###